
import { Product, Testimonial, FrameShape, FaceShape } from './types';

export const SHOP_DETAILS = {
  name: 'DRISHTII EYECARE',
  address: 'Bethuadahari, Nadia Dist, West Bengal - 741126',
  phone: '+91 9064000639',
  whatsapp: '919064000639',
  email: 'contact@drishtiieyecare.com',
  colors: {
    primary: '#007BFF',
    secondary: '#0056b3'
  }
};

const DEFAULT_SIZES = ['Small', 'Medium', 'Large'];
const COLOR_PALETTE = {
  Black: '#000000',
  Grey: '#4B5563',
  Gold: '#D4AF37',
  Silver: '#C0C0C0',
  RoseGold: '#B76E79',
  Brown: '#78350F',
  Tortoise: '#54301a',
  Clear: '#f8fafc',
  MatteBlue: '#1e3a8a',
  Champagne: '#fdf4ff',
};

const MASTER_IMAGES = {
  AVIATOR: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f',
  WAYFARER: 'https://images.unsplash.com/photo-1591076482161-42ce6da69f67',
  OVERSIZED: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083',
  NAVIGATOR: 'https://images.unsplash.com/photo-1577803645773-f96470509666',
  CATEYE: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796',
  CLUBMASTER: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371',
  ROUND: 'https://images.unsplash.com/photo-1502767089025-6572583495f9',
  SQUARE: 'https://images.unsplash.com/photo-1527689368864-3a821dbccc34',
  VINTAGE: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a',
  GLOSSY: 'https://images.unsplash.com/photo-1508296695146-257a814070b4',
};

const generateProducts = (): Product[] => {
  return [
    {
      id: 'm-1',
      name: 'Aviator Teardrop',
      price: 1299,
      category: 'Metal',
      shape: 'Aviator',
      shapes: ['Aviator'],
      image: `${MASTER_IMAGES.AVIATOR}?auto=format&fit=crop&w=800&q=80`,
      description: 'Classic teardrop aviators in high-grade metal with sun block technology.',
      sizes: DEFAULT_SIZES,
      colors: [{ name: 'Black', hex: COLOR_PALETTE.Black }],
      faceShapes: ['Oval', 'Square', 'Heart'],
    },
    {
      id: 'm-2',
      name: 'Wayfarer Trapezoid',
      price: 999,
      category: 'Acetate',
      shape: 'Square',
      shapes: ['Square'],
      image: `${MASTER_IMAGES.WAYFARER}?auto=format&fit=crop&w=800&q=80`,
      description: 'Iconic trapezoid silhouette in premium acetate. Lightweight and durable.',
      sizes: DEFAULT_SIZES,
      colors: [{ name: 'Onyx Black', hex: COLOR_PALETTE.Black }],
      faceShapes: ['Round', 'Oval'],
    },
    {
      id: 'm-3',
      name: 'Oversized Rectangle',
      price: 1999,
      category: 'Premium',
      shape: 'Rectangle',
      shapes: ['Rectangle'],
      image: `${MASTER_IMAGES.OVERSIZED}?auto=format&fit=crop&w=800&q=80`,
      description: 'Luxury oversized rectangle frames for a bold, sophisticated statement.',
      sizes: ['Medium', 'Large'],
      colors: [{ name: 'Deep Grey', hex: COLOR_PALETTE.Grey }],
      faceShapes: ['Oval', 'Round'],
    },
    {
      id: 'm-4',
      name: 'Navigator Squared',
      price: 1299,
      category: 'Metal',
      shape: 'Square',
      shapes: ['Square'],
      image: `${MASTER_IMAGES.NAVIGATOR}?auto=format&fit=crop&w=800&q=80`,
      description: 'Square navigator frames with a rugged, urban aesthetic and flexible fit.',
      sizes: ['Medium', 'Large'],
      colors: [{ name: 'Silver', hex: COLOR_PALETTE.Silver }],
      faceShapes: ['Oval', 'Round'],
    },
    {
      id: 'm-5',
      name: 'Cat-Eye Upsweep',
      price: 1499,
      category: 'Acetate',
      shape: 'Cat-Eye',
      shapes: ['Cat-Eye'],
      image: `${MASTER_IMAGES.CATEYE}?auto=format&fit=crop&w=800&q=80`,
      description: 'Elegant upswept cat-eye frames for a vintage-chic aesthetic.',
      sizes: DEFAULT_SIZES,
      colors: [{ name: 'Tortoise', hex: COLOR_PALETTE.Tortoise }],
      faceShapes: ['Square', 'Diamond', 'Heart'],
    },
    {
      id: 'm-6',
      name: 'Clubmaster Browline',
      price: 1799,
      category: 'Premium',
      shape: 'Square',
      shapes: ['Square'],
      image: `${MASTER_IMAGES.CLUBMASTER}?auto=format&fit=crop&w=800&q=80`,
      description: 'Vintage-inspired browline frames with a modern twist.',
      sizes: DEFAULT_SIZES,
      colors: [{ name: 'Black Gold', hex: COLOR_PALETTE.Black }],
      faceShapes: ['Oval', 'Square'],
    },
    {
      id: 'm-7',
      name: 'Round Bohemian',
      price: 1199,
      category: 'Acetate',
      shape: 'Round',
      shapes: ['Round'],
      image: `${MASTER_IMAGES.ROUND}?auto=format&fit=crop&w=800&q=80`,
      description: 'Perfectly round bohemian frames in handcrafted acetate.',
      sizes: ['Small', 'Medium'],
      colors: [{ name: 'Tortoise', hex: COLOR_PALETTE.Tortoise }],
      faceShapes: ['Square', 'Oval', 'Heart'],
    },
    {
      id: 'm-8',
      name: 'Square Angular',
      price: 1299,
      category: 'Metal',
      shape: 'Square',
      shapes: ['Square'],
      image: `${MASTER_IMAGES.SQUARE}?auto=format&fit=crop&w=800&q=80`,
      description: 'Sharp, angular square frames in lightweight glossy metal.',
      sizes: DEFAULT_SIZES,
      colors: [{ name: 'Gunmetal', hex: COLOR_PALETTE.Grey }],
      faceShapes: ['Round', 'Oval'],
    },
    {
      id: 'm-9',
      name: 'Vintage Tortoise',
      price: 1999,
      category: 'Premium',
      shape: 'Round',
      shapes: ['Round'],
      image: `${MASTER_IMAGES.VINTAGE}?auto=format&fit=crop&w=800&q=80`,
      description: 'Heritage vintage design in authentic tortoise-pattern acetate.',
      sizes: ['Medium'],
      colors: [{ name: 'Vintage Tortoise', hex: COLOR_PALETTE.Tortoise }],
      faceShapes: ['Oval', 'Square', 'Heart'],
    },
    {
      id: 'm-10',
      name: 'Glossy Metal Frame',
      price: 1499,
      category: 'Metal',
      shape: 'Rectangle',
      shapes: ['Rectangle'],
      image: `${MASTER_IMAGES.GLOSSY}?auto=format&fit=crop&w=800&q=80`,
      description: 'Brilliant glossy metal rectangle frames with a polished mirror finish.',
      sizes: DEFAULT_SIZES,
      colors: [{ name: 'Gold', hex: COLOR_PALETTE.Gold }],
      faceShapes: ['Oval', 'Round'],
    },
  ];
};

export const PRODUCTS: Product[] = generateProducts();

export const TESTIMONIALS: Testimonial[] = [
  { id: '1', name: 'Arnab Das', location: 'Bethuadahari', text: 'খুব ভালো চশমা। দামেও সস্তা।', rating: 5 },
  { id: '2', name: 'Priya Sharma', location: 'Kolkata', text: 'Excellent service and quick home eye test.', rating: 5 },
  { id: '3', name: 'Subhash Ghosh', location: 'Nadia', text: 'Best optical shop in Bethuadahari. Recommended.', rating: 4 },
  { id: '4', name: 'Md. Ibrahim', location: 'Debagram', text: 'বাজেট ফ্রেন্ডলি অপটিক্যাল শপ।', rating: 5 },
  { id: '5', name: 'Sneha Gupta', location: 'Bethuadahari', text: 'Virtual try-on helped me choose the right frame!', rating: 5 },
];
